import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface PDFExportOptions {
  fileName: string;
  title: string;
  elementId: string;
}

/**
 * Export a component to PDF
 * @param options - Configuration for PDF export
 */
export async function exportToPDF(options: PDFExportOptions): Promise<void> {
  const { fileName, elementId } = options;

  try {
    const element = document.getElementById(elementId);
    if (!element) {
      throw new Error(`Element with id "${elementId}" not found`);
    }

    // Show a loading indicator (you can customize this)
    const loadingDiv = document.createElement('div');
    loadingDiv.style.cssText = `
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      background: white;
      padding: 20px 40px;
      border-radius: 8px;
      box-shadow: 0 4px 6px rgba(0,0,0,0.1);
      z-index: 9999;
      font-family: sans-serif;
    `;
    loadingDiv.textContent = 'Generating PDF...';
    document.body.appendChild(loadingDiv);

    // Convert the element to canvas
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
    });

    // Remove loading indicator
    document.body.removeChild(loadingDiv);

    // Calculate PDF dimensions
    const imgWidth = 210; // A4 width in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    // Create PDF
    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgData = canvas.toDataURL('image/png');

    // Add image to PDF
    pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);

    // Save PDF
    pdf.save(fileName);
  } catch (error) {
    console.error('Error generating PDF:', error);
    alert('Failed to generate PDF. Please try again.');
  }
}

/**
 * Create a printable report element
 */
export function createPrintableReport(content: {
  title: string;
  subtitle?: string;
  sections: Array<{
    title: string;
    content: string;
  }>;
}): string {
  return `
    <div style="padding: 40px; font-family: system-ui, -apple-system, sans-serif; max-width: 800px; margin: 0 auto;">
      <h1 style="font-size: 28px; font-weight: bold; color: #1a1a1a; margin-bottom: 8px;">${content.title}</h1>
      ${content.subtitle ? `<p style="font-size: 16px; color: #666; margin-bottom: 24px;">${content.subtitle}</p>` : ''}
      ${content.sections.map(section => `
        <div style="margin-bottom: 24px;">
          <h2 style="font-size: 20px; font-weight: 600; color: #333; margin-bottom: 12px;">${section.title}</h2>
          <div style="color: #555; line-height: 1.6;">${section.content}</div>
        </div>
      `).join('')}
      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e5e5; color: #999; font-size: 12px;">
        Generated by QuickCalc Tools • ${new Date().toLocaleDateString()}
      </div>
    </div>
  `;
}
